# This rule will make sure that etl jobs must go on the targeted nodes
# and that they tolerate the taint added by the jobs nag
apiVersion: assignments.director.k8s.io/v1alpha1
kind: PodAssignmentRule
metadata:
  name: etl-jobs
spec:
  targetLabels:
    workload: etl
  scheduling:
    mergeStrategy: OverwriteAll
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: nag.assignments.director.k8s.io/jobs
              operator: In
              values:
              - "etl"
    tolerations:
    - key: nag.assignments.director.k8s.io/jobs
      operator: Equal
      value: etl
