# This group will split up the spot nodes in the cluster. Tainting some for etl
# and the rest for queue jobs. That means that pods which need to be on the spot
# nodes will need to tolerate the taint
apiVersion: assignments.director.k8s.io/v1alpha1
kind: NodeAssignmentGroup
metadata:
  name: jobs
spec:
  targetLabels:
    nodetype-spot: "true"
  assignments:
    - name: "etl"
      mode: LabelAndTaint
      numDesired: 2
  defaultAssignment:
    name: "queue"
    mode: LabelAndTaint
